### ISSUE TITLE
[Feature request] Add additonal size options for UMA frame buffer

### ISSUE THREAD

**Issue by DuckersMcQuack** [CryoByte33/steam-deck-utilities#180]
I want to request additional options for UMA frame buffer, as i do a bit more than just game on my steam deck, and some python stuff needs more than just 4GB shared memory, so i want to request a feature addition to cryoutilities to add options of 6 and 8GB UMA frame buffer if possible. I've tried for a few days to locate the file specifying it, but it's such a niche thing to want, that google had nothing on it, nor did anyone over at steam deck discord, nor linux subchannels in servers in general.

**Comment by CryoByte33** [comment]
UMA Frame buffer size options are not provided by CU itself, I just recommend 4GB. The actual options are provided by Valve's BIOS and in older versions you could actually use Smokeless_UMAF to set up to 8GB of UMA Buffer.

Since theres no way I can personally change the options available for UMA, I'll be closing this issue, sorry!

**Comment by DuckersMcQuack** [comment]
No need to be sorry, as i wanna understand if it can or not as well :P
So, with latest bios/SteamOS, It can't be done? And are there any tools to alter it? Unless you know if there's a way to get python stuffs to read shared vram/ram like games does? :P As games will use as much as it needs, but python annoyingly only reads from uma

Also, does me commenting even if it closes, reopen it?

**Comment by CryoByte33** [comment]
Nope, it should stay closed.

As far as I know there isn't anything that can be done on the latest BIOS. We can read the set value but not alter it from inside the OS as it's a firmware-level change. I know in the past that there was some progress towards flashing custom BIOS onto the Deck, but it relied on using a proprietary program (against the licensing) to sign the BIOS file and allow it to be installed, so it was never made public.

That said, I've been pretty busy with a new job this last month so I haven't had the luxury of keeping up with the latest news. If you're interested in learning more about the BIOS changes and everything then I'd actually suggest my Discord since there are a lot of users really pushing the limits in there, even while I'm busy 🙂
