### ISSUE TITLE
Add "(Default)" to stock/default values

### ISSUE THREAD

**Issue by Hieberrr** [CryoByte33/steam-deck-utilities#21]
If possible, can we add the text "(Default)" to the default selectable values when using CryoUtilities? If users want to revert to default or uninstall, it would be great if there there was a way for them to easily identify the stock values. 

Alternatively, perhaps the uninstaller can have an option to revert to stock values?

**Comment by CryoByte33** [comment]
Regarding the "default" values, swappiness already lists it in the heading. Would you like it next to the actual value in the list, itself?

Regarding the uninstaller, I was asked to keep the script "one-shot" and thus had it leave the values alone. In the next major update, I plan to have the uninstaller ask if the user wishes to revert or not, would that be adequate?

**Comment by Hieberrr** [comment]
Thanks, @CryoByte33.

I think having it beside the actual value in the list would be beneficial so that users either (1) know what to set it to if they want to revert, as well as (2) so hey know what to avoid if they want to use a bigger swap value. I figure a lot of users who are trying this may also be first time users of something like this. 

Regarding the uninstaller, that would be fantastic, if possible.

**Comment by CryoByte33** [comment]
Hmmm alright, I can do that. The only issue is that I'll have to add logic handling that specific option, since Zenity automatically uses the selected option as the argument. Basically, I'll have to convert it prior to using the value.

I'll likely put both of these improvements in the initial release of the major update. I'm converting everything here (and a TON more that's not public) into a Go application that should be more maintainable and let me do some really cool stuff. I'd expect it in a month or so at the current rate, so don't worry if you don't see anything before then 🙂

Thank you for the suggestions! I'll keep this issue open as an improvement until the update drops!

**Comment by CryoByte33** [comment]
Quick update here, both of these have been implemented in the upcoming version and should be released in the next month or so.

**Comment by CryoByte33** [comment]
The update has been released, details at https://youtu.be/C9EjXYZUqUs, closing this issue!
