### ISSUE TITLE
Create written explanation of each tweak.

### ISSUE THREAD

**Issue by CryoByte33** [CryoByte33/steam-deck-utilities#50]
Each tweak should have the file that it modifies, value, tmpfiles unit, and purpose specified.

**Comment by CryoByte33** [comment]
This was completed with #66

**Comment by danteali** [comment]
Can we also get an explanation added for the data management actions?

I've watched the video but I'm still not clear on exactly what actions are taken when moving files between storage locations. My concern is that I've already moved some game files to the SD card and created symlinks and I don't know whether I can use the Utility to move additional files or if it will break something due to me having already moved stuff.

Having a detailed breakdown of what commands etc are run would help with assessing whether I can use the Utility or if it will cause any issues on my end. 

Thanks

**Comment by CryoByte33** [comment]
@danteali I can create a written explanation of the "process", but it won't be a 1:1 of each command, since it's almost entirely Go code and largely doesn't use normal commands. For example, I use io.Copy which is _similar_ to a cp command, but not identical.

As for whether you can use the script or not, it will likely create breakage if your data is in the incorrect place on the SD card. 

Folders in `/home/deck/.local/share/Steam/steamapps/compatdata` move to `/run/media/mmcblk0p1/cryoutilities_steam_data/compatdata` and get symlinked back, and folders in `/home/deck/.local/share/Steam/steamapps/shadercache` move to `/run/media/mmcblk0p1/cryoutilities_steam_data/shadercache` and get symlinked back.

**Comment by danteali** [comment]
Thanks, even it it was just an example using a random folder name that would help with understanding what exactly gets moved.

I've already symlinked some of the folders inside `/home/deck/.local/share/Steam/steamapps/compatdata` to `/run/media/mmcblk0p1/Steam/steamapps/compatdata` so these symlinks might be fine since yours would just symlink to another SD card folder. But I'll probably just move my SD card files to your folder and recreate my symlinks.

But I've also moved the entire `shadercache` folder to the SD card so not quite sure if your commands will break anything or if they will just create additional symlinks inside the existing symlinked folder. I'll need to do a quick test on my own Linux machine to see what happens if you try to create a symlink in an already symlinked folder.

But it would be helpful if the commands were documented as that would make it easier to test/verify before using. But if you have other priorities then this one obviously isn't urgent at all.

**Comment by CryoByte33** [comment]
> I've already symlinked some of the folders inside /home/deck/.local/share/Steam/steamapps/compatdata to /run/media/mmcblk0p1/Steam/steamapps/compatdata so these symlinks might be fine since yours would just symlink to another SD card folder. But I'll probably just move my SD card files to your folder and recreate my symlinks.

> But I've also moved the entire shadercache folder to the SD card so not quite sure if your commands will break anything or if they will just create additional symlinks inside the existing symlinked folder. I'll need to do a quick test on my own Linux machine to see what happens if you try to create a symlink in an already symlinked folder.

This will probably work and just create additional symlinks as you mentioned.

But yeah, I'll try to get it documented. I need to create a "move game data back to internal" function as well, so this will likely be part of that.
