### ISSUE TITLE
[Feature request] Decky plugin

### ISSUE THREAD

**Issue by oemsysadm** [CryoByte33/steam-deck-utilities#78]
Any chance you'll make a plugin that can be used with Decky Loader for this?

**Comment by CryoByte33** [comment]
I would love to but Decky doesn't allow for "blocking" operations. Basically, if someone decided to launch a game or put the Deck to sleep in the middle of a swap resize or data sync... it would not be a fun time.

**Comment by bugworm** [comment]
On top of that most of the stuff that plugin is doing is not something that shoud be done frequently, so I don't see a problem to go to a desktop mode for this one. Maybe memory tuning can be added, but some of that is already part of System Toolbox, it could be just included there instead of writing completely new plugin

**Comment by CryoByte33** [comment]
Alright, yeah. If others agree then I'll close this for now, pending Decky getting proper blocking behavior.

Thank you for opening the issue!
