### ISSUE TITLE
MicroSD cards CAN be permamently killed if trim command is executed on them

### ISSUE THREAD

**Issue by samip5** [CryoByte33/steam-deck-utilities#9]
I would highly suggest to ask the user if they want to enable it on the local SSD only, or for MicroSD too and include an disclaimer that enabling it on the card can in some cases make the card useless specially if it's not from a well known brand.

**Comment by ipkpjersi** [comment]
Doesn't the scheuled trim run on MicroSD cards too, or am I thinking of the immediate trim?

Either way, I'm pretty sure it should be disabled by default for MicroSD cards entirely and made opt-in only.

**Comment by CryoByte33** [comment]
I never even saw this, sorry! The current code:
1. Doesn't allow for scheduled TRIM on SteamOS 3.4 and higher
2. Allows for immediate TRIM on all versions, but ONLY on /home.
3. Allows for scheduled TRIM on versions lower than 3.4, and respects the fstab mounting options. I haven't seen an unsupported MicroSD get mounted with "TRIM supported" options yet, but I could have just been lucky.

Regardless, I'm deep in development of a new version that will omit TRIM entirely since Valve implemented it natively 🙂

**Comment by ipkpjersi** [comment]
Oh, even better, that's my fault for checking old issues lol!
